improve: replace JsDelivr with SUStech and domains convergence
naiba/nezha pull request #319
Opened 2024-02-16 08:13 UTC by famousprince

-  JsDelivr has poor performace in China, so this replacement will greatly improve loading speed for users in China.
- Unify resources loaded from ByteDance public libraries to `lf6-cdn-tos.bytecdntp.com` to converge DNS and HTTP requests.
- SUStech mirror has only one server located in China, so overseas users may feels slow when loading. Therefore Zstatic may be another choice since its' both Mainland China and overseas CDN servers, like:

`https://s4.zstatic.net/ajax/libs/bootstrap-icons/1.11.2/font/bootstrap-icons.min.css`
`https://s4.zstatic.net/ajax/libs/flag-icons/7.0.0/css/flag-icons.min.css`

![Screenshot 2024-02-16 161220](https://github.com/naiba/nezha/assets/121652515/1c354333-15e8-4968-baea-8daceb8e5165)
![Screenshot 2024-02-16 161254](https://github.com/naiba/nezha/assets/121652515/998ad9ed-9971-4197-a9c3-cf8b213d560f)

2024-02-18 06:51 UTC, naiba commented
把sustech换成其他的吧，这种不知道能运营多久

Zstatic不是公司运营，也换成其他的

2024-02-18 06:58 UTC, famousprince commented
https://github.com/SUSTech-CRA/ccse-mirrors-web/commits/master/site/help/cdnjs.md

https://mirrors.cernet.edu.cn/list/cdnjs

SUStech 运营两年有余，是中国高校唯一维护 CDNJS 镜像的，稳定性是有的，也能一定程度上改善 JsDelivr 加载缓慢的问题

2024-02-18 07:16 UTC, naiba requested changes
高校唯一就代表风险

2024-02-18 09:48 UTC, famousprince commented
Try `cdn.jsdelivr.net` -> `fastly.jsdelivr.net` ?

2024-02-18 11:58 UTC, naiba commented
> Try `cdn.jsdelivr.net` -> `fastly.jsdelivr.net` ?

字节里没有吗

2024-02-20 09:02 UTC, ysicing commented
https://cdn.onmicrosoft.cn/ 这个我用了很久，感觉还挺稳定的

2024-02-20 09:09 UTC, naiba commented
> [cdn.onmicrosoft.cn](https://cdn.onmicrosoft.cn/) 这个我用了很久，感觉还挺稳定的

公司维护的CDN可用的前提下不选择个人维护的CDN，面板能力很大不能冒风险

2024-03-23 04:40 UTC, closed without merging